#!/bin/sh

set -e

(gem spec bundler -v '~> 1.6.0' > /dev/null 2>&1) || gem install bundler -v '~> 1.6.0' --no-rdoc --no-ri

rm -rf .bundle/config
bundle install --binstubs .bundle/bin --path .bundle

